# Usa uma imagem do Node.js para construir o projeto
FROM node:20 AS build

# Define o diretório de trabalho no container
WORKDIR /frontend

# Copia os arquivos do projeto para o container
COPY package.json package-lock.json ./
RUN npm install

# Copia o restante do código
COPY . .

# Expondo a porta que o Vite usa
EXPOSE 5173

# Comando padrão para rodar o Vite
CMD ["npm", "run", "dev", "--", "--host"]
