version: '3.8'

services:
  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: macagucho
      MYSQL_DATABASE: webnovel_db
      MYSQL_ROOT_HOST: '%'
    ports:
      - "3307:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-u", "root", "-pmacagucho"]
      interval: 5s
      timeout: 30s
      retries: 10
    networks:
      - app-network
    volumes:
      - mysql-data:/var/lib/mysql
      - ${FULL_SQL_PATH}
    restart: unless-stopped

  frontend:
    image: ${REGISTRY}/frontend:${IMAGE_TAG}
    build: ./frontend
    ports:
      - "5173:5173"
    depends_on:
      - backend
    environment:
      VITE_API_URL: http://backend:3001/
    networks:
      - app-network
    restart: unless-stopped

  backend:
    image: ${REGISTRY}/backend:${IMAGE_TAG}
    build: ./backend
    ports:
      - "3001:3001"
    environment:
      DB_HOST: mysql
      DB_USER: root
      DB_PASSWORD: macagucho
      DB_NAME: webnovel_db
    depends_on:
      mysql:
        condition: service_healthy
    networks:
      - app-network
    restart: unless-stopped

networks:
  app-network:
    driver: bridge

volumes:
  mysql-data:  # Volume fixo nomeado para persistência do MySQL
